services:
  - type: web
    name: api-dannos
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000y"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1