services:
  - type: web
    name: api-dannos
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python main.py"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.6"
    disk:
      name: data
      mountPath: /opt/render/project/src
      sizeGB: 1